services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma generate && npm start"
    restart: always

  studio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma generate && npx prisma studio --hostname 0.0.0.0 --port 5555"
